### ISSUE TITLE
Django Auto Instrumentation Not Working

### ISSUE THREAD

**Issue by tjohander-splunk** [signalfx/splunk-otel-python#249]
I'm trying to get Auto Instrumentation working for a sample Django application.  My project repo is [here](https://github.com/tjohander-splunk/django-autoinstrumentation).  Details of my project configuration and bootstrapping process is detailed in the repo's `README.md`

The output of `pip freeze > requirements.txt` is but for reference, here is what's been installed in the `venv`:
```
asgiref==3.5.2
backoff==1.11.1
Deprecated==1.2.13
Django==4.0.6
googleapis-common-protos==1.56.4
grpcio==1.47.0
opentelemetry-api==1.11.1
opentelemetry-exporter-jaeger-thrift==1.11.1
opentelemetry-exporter-otlp-proto-grpc==1.11.1
opentelemetry-instrumentation==0.30b1
opentelemetry-instrumentation-aws-lambda==0.30b1
opentelemetry-instrumentation-dbapi==0.30b1
opentelemetry-instrumentation-django==0.30b1
opentelemetry-instrumentation-grpc==0.30b1
opentelemetry-instrumentation-logging==0.30b1
opentelemetry-instrumentation-sqlite3==0.30b1
opentelemetry-instrumentation-urllib==0.30b1
opentelemetry-instrumentation-wsgi==0.30b1
opentelemetry-propagator-aws-xray==1.0.1
opentelemetry-propagator-b3==1.11.1
opentelemetry-proto==1.11.1
opentelemetry-sdk==1.11.1
opentelemetry-semantic-conventions==0.30b1
opentelemetry-util-http==0.30b1
protobuf==3.20.1
six==1.16.0
splunk-opentelemetry==1.6.0
sqlparse==0.4.2
thrift==0.16.0
typing_extensions==4.3.0
wrapt==1.14.1
```

And in my `manage.py` I've tried both adding the call `DjangoInstrumentor().instrument()`, as well as bootstrapping the application with `splunk-py-trace python3 ./manage.py runserver`.  I am not using `wsgi` for this local example.

I've run the collector with both the `docker-compose` based container for the Collector as well as this command to get an instance of the collector running with the defaults: 
```bash
docker run --rm -e SPLUNK_ACCESS_TOKEN=<my-token> -e SPLUNK_REALM=us1 \
    -p 13133:13133 -p 14250:14250 -p 14268:14268 -p 4317:4317 -p 6060:6060 \
    -p 7276:7276 -p 8888:8888 -p 9080:9080 -p 9411:9411 -p 9943:9943 \
    --name otelcol quay.io/signalfx/splunk-otel-collector:latest
```

**Comment by owais** [comment]
My otel collector config:

```yaml
receivers:
  otlp:
    protocols:
        grpc:
            endpoint: 0.0.0.0:4317
        http:
            endpoint: 0.0.0.0:55681

exporters:
  logging:
      loglevel: debug


service:
  pipelines:
    traces:
      receivers: [otlp]
      exporters: [logging]
```
